Trying to remove nginx from the equation

diff --git a/bin/control b/bin/control
--- a/bin/control
+++ b/bin/control
@@ -35,17 +35,17 @@ function start() {
 
   _build_config
 
-  echo "Starting Nginx"
-  if [ -f "$NGINX_EXEC" ]; then
-      if [ -f "$OPENSHIFT_REPO_DIR/nginx.conf.erb" ]; then
-          oo-erb $OPENSHIFT_REPO_DIR/nginx.conf.erb > $OPENSHIFT_REPO_DIR/nginx.conf
-      fi
+  #echo "Starting Nginx"
+  #if [ -f "$NGINX_EXEC" ]; then
+  #    if [ -f "$OPENSHIFT_REPO_DIR/nginx.conf.erb" ]; then
+  #        oo-erb $OPENSHIFT_REPO_DIR/nginx.conf.erb > $OPENSHIFT_REPO_DIR/nginx.conf
+  #    fi
       # nginx will always use the prefix defined at compile time unless an absolute path to the conf file is given
-      "$NGINX_EXEC" -c "$NGINX_CONFIG_FILE" 2>&1
-      [ "$?" == "0" ] && wait_for_pid_file $NGINX_PID_FILE
-  else
-      echo "WARN: Could not find the compiled application versions/$NGINX_VERSION/bin/nginx, will not start"
-  fi
+  #    "$NGINX_EXEC" -c "$NGINX_CONFIG_FILE" 2>&1
+  #    [ "$?" == "0" ] && wait_for_pid_file $NGINX_PID_FILE
+  #else
+  #    echo "WARN: Could not find the compiled application versions/$NGINX_VERSION/bin/nginx, will not start"
+  #fi
 
   echo "Starting Kibana"
   if [ -f "$OPENSHIFT_REPO_DIR/kibana.yml.erb" ]; then
